repos:
  - repo: local
    hooks:
      - id: tofu-fmt
        name: OpenTofu fmt
        language: script
        entry: .pre-commit-hooks/tofu-fmt.sh
        files: \.tf$
        pass_filenames: false

      - id: tofu-validate
        name: OpenTofu validate
        language: script
        entry: .pre-commit-hooks/tofu-validate.sh
        files: \.tf$
        pass_filenames: false

      - id: prettier
        name: Prettier format
        language: node
        entry: npx prettier --write
        types_or: [javascript, jsx, ts, tsx, css, json, yaml, markdown]
        pass_filenames: true

      - id: ng-test
        name: Angular unit tests
        language: node
        entry: npx ng test --watch=false
        pass_filenames: false
        files: ^src/.*\.(ts|html|scss)$
